In [5]:
import numpy as np

Basic Array  creation

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [18]:
arr = [1,2,3.5,"hello"]
arr

[1, 2, 3.5, 'hello']

In [9]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [47]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [19]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr = np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr = np.ones((7,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [36]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation function

In [37]:
np.random.rand(10)

array([0.56815203, 0.17617986, 0.50193204, 0.26355622, 0.29412925,
       0.9445606 , 0.2536514 , 0.38768638, 0.37798951, 0.26018694])

In [38]:
np.random.randn(10)

array([-0.23620241,  1.04683253, -0.1885803 ,  0.04528834, -0.29373914,
        1.70171435,  0.99782547, -0.31800952,  1.62733887, -0.4244678 ])

In [42]:
np.random.randint(10,20,10)


array([18, 16, 17, 12, 11, 18, 18, 17, 11, 12])

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Attributes

In [44]:
arr.size

9

In [45]:
arr.shape

(3, 3)

In [46]:
arr.dtype

dtype('int64')

Array Methods

In [59]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.min()

np.int64(1)

In [61]:
arr.max()

np.int64(9)

In [62]:
arr.sum()

np.int64(45)

In [66]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [67]:
arr.mean()

np.float64(5.0)

In [69]:
arr.std()

np.float64(2.581988897471611)

In [70]:
arr.argmax()

np.int64(8)

In [71]:
arr.argmin()

np.int64(0)

In [72]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])