#### **1. Introduction to NumPy**

#### **Task 1**: Import the NumPy library and print its version.

In [ ]:
import numpy as np
print(np.version)


<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [ ]:
arr =np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [ ]:
arr =np.random.rand(3,4)
print(arr)
print("Shape =",arr.shape)
print("Data Type =", arr.dtype)


[[0.42397231 0.09162321 0.21406242 0.40141528]
 [0.90381461 0.59698144 0.71950397 0.33553186]
 [0.53409394 0.64560214 0.41506143 0.87035915]]
Shape = (3, 4)
Data Type = float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [ ]:
arr =np.linspace(0,10,50)
print(arr)


[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print("Python List Addition =", list1 + list2)
arr1 =np.array(list1)
arr2 =np.array(list2)

print("Numpy Addition =", arr1 + arr2)



Python List Addition = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Numpy Addition = [ 7  9 11 13 15]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [ ]:
arr =np.zeros((3,4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [ ]:
arr =np.ones((2,5),dtype=float)
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [ ]:
arr = np.arange(10,51,5)
print(arr)


[10 15 20 25 30 35 40 45 50]


**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [ ]:
identity_matrix =np.eye(3)
identity_matrix =np.identity(3)
print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [ ]:
arr =np.random.randint(1,20,(4,4))
print(arr)


[[ 7 19  4 16]
 [16  8 19  6]
 [ 6  7  8 11]
 [12 11  7 17]]


---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [ ]:
arr1d =np.arange(1,16)
print(arr1d)
sliced_arr =arr1d[3:9]
print(sliced_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[4 5 6 7 8 9]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [ ]:
matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
element =matrix[1,2]
print(element)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [ ]:
arr =np.arange(1,17).reshape(4,4)
print(arr[2:4,2:4])


[[11 12]
 [15 16]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [ ]:
arr = np.random.randint(10,51,(5,5))
arr[0] =100
print(arr)


[[100 100 100 100 100]
 [ 34  44  15  13  10]
 [ 36  47  36  48  32]
 [ 41  32  38  27  31]
 [ 24  40  21  49  33]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [ ]:
arr =np.arange(1,11)
print(arr[arr > 5])


[ 6  7  8  9 10]
